In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data_DGA.csv', index_col = 0)

In [3]:
df = df.iloc[:-1,:]

In [4]:
df

h2    ch4    c2h6   c2h4     c2h2  act
0.0    117   17.0   1.000    3.0    1.000  1.0
1.0    407   28.0  15.000   21.0    0.001  1.0
2.0    183    6.0   0.001    5.0    0.001  1.0
3.0    166   21.0  38.000    6.0    0.001  1.0
4.0    105   23.0  13.000    4.0    3.000  1.0
...    ...    ...     ...    ...      ...  ...
559.0   56   61.0  75.000   32.0   31.000  2.0
560.0  217  286.0  14.000  458.0  884.000  3.0
561.0  441  207.0  43.000  224.0  261.000  3.0
562.0  127   24.0   0.001   32.0   81.000  3.0
563.0  176  205.9  47.700   75.7   68.700  3.0

[564 rows x 6 columns]

In [5]:
df['h2'] = pd.to_numeric(df['h2'],errors='coerce')
df['ch4'] = pd.to_numeric(df['ch4'],errors='coerce')
df['c2h6'] = pd.to_numeric(df['c2h6'],errors='coerce')
df['c2h4'] = pd.to_numeric(df['c2h4'],errors='coerce')
df['act'] = pd.to_numeric(df['act'],errors='coerce')


In [6]:
df.dtypes

h2      float64
ch4     float64
c2h6    float64
c2h4    float64
c2h2    float64
act     float64
dtype: object

In [7]:
df = df.reset_index(drop=True)

In [8]:
df

h2    ch4    c2h6   c2h4     c2h2  act
0    117.0   17.0   1.000    3.0    1.000  1.0
1    407.0   28.0  15.000   21.0    0.001  1.0
2    183.0    6.0   0.001    5.0    0.001  1.0
3    166.0   21.0  38.000    6.0    0.001  1.0
4    105.0   23.0  13.000    4.0    3.000  1.0
..     ...    ...     ...    ...      ...  ...
559   56.0   61.0  75.000   32.0   31.000  2.0
560  217.0  286.0  14.000  458.0  884.000  3.0
561  441.0  207.0  43.000  224.0  261.000  3.0
562  127.0   24.0   0.001   32.0   81.000  3.0
563  176.0  205.9  47.700   75.7   68.700  3.0

[564 rows x 6 columns]

In [9]:
print(df['act'].nunique(dropna = True))

6


In [10]:
X = df.iloc[:, :5]
X

h2    ch4    c2h6   c2h4     c2h2
0    117.0   17.0   1.000    3.0    1.000
1    407.0   28.0  15.000   21.0    0.001
2    183.0    6.0   0.001    5.0    0.001
3    166.0   21.0  38.000    6.0    0.001
4    105.0   23.0  13.000    4.0    3.000
..     ...    ...     ...    ...      ...
559   56.0   61.0  75.000   32.0   31.000
560  217.0  286.0  14.000  458.0  884.000
561  441.0  207.0  43.000  224.0  261.000
562  127.0   24.0   0.001   32.0   81.000
563  176.0  205.9  47.700   75.7   68.700

[564 rows x 5 columns]

In [11]:
y = df.iloc[:, -1]

In [12]:
y

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
559    2.0
560    3.0
561    3.0
562    3.0
563    3.0
Name: act, Length: 564, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state=42)

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 1)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [15]:
y_pred = classifier.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [17]:
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[ 5  1  0  0  0  0]
 [ 0  4  3  0  0  0]
 [ 0  1 13  0  0  0]
 [ 0  1  0 11  0  0]
 [ 0  0  0  0  9  2]
 [ 0  0  0  0  1  6]]
Classification Report:
              precision    recall  f1-score   support

         1.0       1.00      0.83      0.91         6
         2.0       0.57      0.57      0.57         7
         3.0       0.81      0.93      0.87        14
         4.0       1.00      0.92      0.96        12
         5.0       0.90      0.82      0.86        11
         6.0       0.75      0.86      0.80         7

    accuracy                           0.84        57
   macro avg       0.84      0.82      0.83        57
weighted avg       0.85      0.84      0.84        57

Accuracy: 0.8421052631578947


In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)


In [17]:
from xgboost.sklearn import XGBClassifier

In [38]:
xgb1 = XGBClassifier(
 learning_rate =0.05,
 n_estimators=700,
 max_depth=6,
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'multi:softprob',
 nthread=8,
 scale_pos_weight=2,
 seed=27)


In [35]:
xgb1.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=None, n_estimators=700, n_jobs=1,
              nthread=8, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=2, seed=27,
              silent=None, subsample=0.8, verbosity=1)

In [36]:
preds = xgb1.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(preds,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 91.23%


In [96]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [99]:
result = confusion_matrix(y_test, preds)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, preds)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,preds)
print("Accuracy:",result2)

Confusion Matrix:
[[ 6  0  0  0  0  0]
 [ 0  4  3  0  0  0]
 [ 0  0 14  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  2  9  0]
 [ 0  0  0  0  0  7]]
Classification Report:
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00         6
         2.0       1.00      0.57      0.73         7
         3.0       0.82      1.00      0.90        14
         4.0       0.86      1.00      0.92        12
         5.0       1.00      0.82      0.90        11
         6.0       1.00      1.00      1.00         7

    accuracy                           0.91        57
   macro avg       0.95      0.90      0.91        57
weighted avg       0.93      0.91      0.91        57

Accuracy: 0.9122807017543859


In [41]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)

In [42]:
neigh.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [43]:
y_pred = neigh.predict(X_test)

In [44]:
accuracy = accuracy_score(y_pred,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 84.21%


In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaler = StandardScaler()

In [30]:
X_ts = scaler.fit_transform(X_train)
X_tes = scaler.fit_transform(X_test)

In [31]:
neigh.fit(X_ts,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [32]:
y_tes = neigh.predict(X_tes)

In [33]:
accuracy = accuracy_score(y_tes,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 33.33%


In [34]:
leaf_size = list(range(1,50))
n_neighbors = list(range(1,30))
p=[1,2]
hyperparameters = dict(leaf_size=leaf_size, n_neighbors=n_neighbors, p=p)

In [35]:
knn_2 = KNeighborsClassifier()

In [36]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(knn_2, hyperparameters, cv=10)

In [40]:
clf = GridSearchCV(knn_2, hyperparameters, cv=10)

In [ ]:
clf.fit(X_train,y_train)

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [82]:
clf = RandomForestClassifier(max_depth=13, random_state=42)

In [83]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=13, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [84]:
y_t = clf.predict(X_test)

In [85]:
accuracy = accuracy_score(y_t,y_test)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 87.72%


In [89]:
for i in range(1,20):
    clf = RandomForestClassifier(max_depth=i, random_state=42)
    clf.fit(X_train, y_train)
    y_t = clf.predict(X_test)
    accuracy = accuracy_score(y_t,y_test)
    print("Accuracy: %.2f%%" % (accuracy * 100.0))
    
    

Accuracy: 50.88%
Accuracy: 57.89%
Accuracy: 61.40%
Accuracy: 68.42%
Accuracy: 71.93%
Accuracy: 84.21%
Accuracy: 85.96%
Accuracy: 84.21%
Accuracy: 85.96%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
Accuracy: 87.72%
